version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A upload_file_api worker -l info
    volumes:
      - .:/app
    depends_on:
      - web
    restart: "on-failure"

  redis:
    image: redis:latest

    ports:
      - "6379:6379"